# Podfile for the iOS export.
#
# This file is the template the Godot iOS export plugin copies into
# the generated Xcode project's directory. It is merged with the
# project's own Podfile (if any) by CocoaPods when the user runs
# `pod install`.

platform :ios, '14.0'
use_frameworks! :linkage => :static
inhibit_all_warnings!

target 'Godot' do
  project 'Godot.xcodeproj'

  # The bridge that talks to the Meta SDK
  pod 'GodotMetaSdk', :path => './addons/meta_sdk/ios/'

  # The Meta SDK itself
  pod 'FBSDKCoreKit',    '~> 18.0'
  pod 'FBSDKLoginKit',   '~> 18.0'
  pod 'FBSDKShareKit',   '~> 18.0'
  pod 'FBAudienceNetwork', '~> 6.15'

  # godot-cpp
  pod 'godot-cpp', '~> 4.5'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      end
    end
  end
end
